<?php

namespace App\GraphQL;

use App\Models\User;
use App\Shared\GraphqlResolver;
use Illuminate\Database\Eloquent\Model;

/**
 * @property User $model
 */
class UserResolver extends GraphqlResolver
{

  public function getExcluded(array $array): array
  {
    return ["avatar"];
  }

  protected function afterUpdate()
  {
    if (isset($this->additionalArguments['avatar'])){
      $this->model
        ->addMedia($this->additionalArguments['avatar'])
        ->preservingOriginal()->toMediaCollection('avatar');
      $this->model->refresh();
    }
  }

  protected function transformArguments(array $arguments)
  {
    if (isset($arguments['password'])){
      unset($arguments['password_confirmation']);
      $arguments['password'] = \Hash::make($arguments['password']);
    }
    return parent::transformArguments($arguments); // TODO: Change the autogenerated stub
  }

  public function makeModel(): Model
  {
    return auth()->user();
  }
}
